posts/urls.py
from .views import post_comment_create_and_list_view, like_unlike_post, PostDelete, PostUpdate
from django.urls import path

app_name = "posts"

urlpatterns = [
    path("", post_comment_create_and_list_view, name="main-post-view"),
    path("liked/", like_unlike_post, name="like-post-view"),
    path("<int:pk>/delete/", PostDelete.as_view(), name="post-delete-view"),
    path("<int:pk>/update/", PostUpdate.as_view(), name="post-update-view"),
]

profiles/urls.py
from django.urls import path

from .views import (ProfileDetailView, ProfileListView, accept_invitation,
                    invite_profiles_list_view, invites_recieved_view,
                    my_profile_view, reject_invitation, remove_friends,
                    send_invitation)

app_name = "profiles"

urlpatterns = [
    path("", ProfileListView.as_view(), name="all-profiles-view"),
    path("accept-invitation/", accept_invitation, name="accept-invitation-view"),
    path("send-invite/", send_invitation, name="send-invite-view"),
    path("myProfile/", my_profile_view, name="my-profile-view"),
    path("my-invites/", invites_recieved_view, name="my-invites-view"),
    path("to-invite/", invite_profiles_list_view, name="to_invite_profiles-view"),
    path("remove-friends/", remove_friends, name="remove-friends-view"),
    path("<slug>/", ProfileDetailView.as_view(), name="profile-detail-view"),
    path("reject-invitation/", reject_invitation, name="reject-invitation-view"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home-view"),
    path("accounts/", include("allauth.urls")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("posts/", include("posts.urls", namespace="posts")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.urls import reverse

# Create your models here.


class ProfileManager(models.Manager):
    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles

    def get_all_profiles_to_invite(self, sender):

        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(reciever=profile))

        accepted = set([])

        for rel in qs:
            if rel.status == "accepted":
                accepted.add(rel.reciever)
                accepted.add(rel.sender)

        available = [profile for profile in profiles if profile not in accepted]

        return available


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="No bio...", max_length=300)
    email = models.EmailField(blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default="avatar.png", upload_to="avatars/")
    friends = models.ManyToManyField(User, related_name="friends", blank=True)
    slug = models.SlugField(unique=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProfileManager()

    def __str__(self) -> str:
        return f"{self.user.username}-{self.created}"

    def get_absolute_url(self):
        return reverse("profiles:profile-detail-view", kwargs={"slug": self.slug})

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for like in likes:
            if like.value == "Like":
                total_liked += 1

        return total_liked

    def get_likes_recieved_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()

        return total_liked

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if (
            self.first_name != self.__initial_first_name
            or self.last_name != self.__initial_last_name
            or self.slug == ""
        ):
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOICES = (
    ("send", "send"),
    ("accepted", "accepted"),
)


class RelationshipManager(models.Manager):
    def invitations_recieved(self, reciever):
        qs = Relationship.objects.filter(reciever=reciever, status="send")
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="sender")
    reciever = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="reciever"
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.reciever}-{self.status}"

profiles/forms.py
from django import forms

from .models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["first_name", "last_name", "bio", "avatar"]

profiles/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, ListView

from .forms import ProfileModelForm
from .models import Profile, Relationship

# Create your views here.


@login_required
def my_profile_view(request):

    profile = Profile.objects.get(user=request.user)

    form = ProfileModelForm(
        request.POST or None, request.FILES or None, instance=profile
    )

    confirm = False

    if request.method == "POST":
        if form.is_valid():
            form.save()
            confirm = True

    context = {"profile": profile, "form": form, "confirm": confirm}

    return render(request, "profiles/myProfile.html", context)


@login_required
def invites_recieved_view(request):

    profile = Profile.objects.get(user=request.user)

    qs = Relationship.objects.invitations_recieved(profile)

    results = list(map(lambda x: x.sender, qs))

    is_empty = False
    if len(results) == 0:
        is_empty = True

    context = {"qs": results, "is_empty": is_empty}

    return render(request, "profiles/my_invites.html", context)


@login_required
def accept_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        sender = Profile.objects.get(pk=pk)
        reciever = Profile.objects.get(user=request.user)

        rel = get_object_or_404(Relationship, sender=sender, reciever=reciever)
        if rel.status == "send":
            rel.status = "accepted"
            rel.save()

    return redirect("profiles:my-invites-view")


@login_required
def reject_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        sender = Profile.objects.get(pk=pk)
        reciever = Profile.objects.get(user=request.user)

        rel = get_object_or_404(Relationship, sender=sender, reciever=reciever)
        rel.delete()

    return redirect("profiles:my-invites-view")


@login_required
def invite_profiles_list_view(request):

    qs = Profile.objects.get_all_profiles_to_invite(request.user)

    context = {"qs": qs}

    return render(request, "profiles/to_invite_profiles_list.html", context)


class ProfileDetailView(LoginRequiredMixin, DetailView):

    model = Profile
    template_name = "profiles/profile_detail.html"

    def get_object(self):
        slug = self.kwargs["slug"]
        proifle = Profile.objects.get(slug=slug)
        return proifle

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(reciever=profile)

        rel_reciver = []
        rel_sender = []

        for item in rel_r:
            rel_reciver.append(item.reciever.user)

        for item in rel_s:
            rel_sender.append(item.sender.user)

        context["rel_reciver"] = rel_reciver
        context["rel_sender"] = rel_sender
        context["posts"] = self.get_object().get_all_authors_posts()
        context["len_posts"] = (
            True if len(self.get_object().get_all_authors_posts()) > 0 else False
        )

        return context


class ProfileListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return Profile.objects.get_all_profiles(self.request.user)

    context_object_name = "qs"

    template_name = "profiles/profiles_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(reciever=profile)

        rel_reciver = []
        rel_sender = []

        for item in rel_r:
            rel_reciver.append(item.reciever.user)

        for item in rel_s:
            rel_sender.append(item.sender.user)

        context["rel_reciver"] = rel_reciver
        context["rel_sender"] = rel_sender
        context["is_empty"] = False

        if len(self.get_queryset()) == 0:
            context["is_empty"] = True

        return context


@login_required
def send_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        sender = Profile.objects.get(user=request.user)
        reciever = Profile.objects.get(pk=pk)

        Relationship.objects.create(sender=sender, reciever=reciever, status="send")

        return redirect(request.META.get("HTTP_REFERER"))

    return redirect("profiles:my-profile-view")


@login_required
def remove_friends(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        sender = Profile.objects.get(user=request.user)
        reciever = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(reciever=reciever))
            | (Q(sender=reciever) & Q(reciever=sender))
        )

        rel.delete()

        return redirect(request.META.get("HTTP_REFERER"))

    return redirect("profiles:my-profile-view")

profiles/templates/profiles/myProfile.html
{% extends "base.html" %} {% block title %} my profile {% endblock title %}
{% block content %} <h2>My Profile {{ profile }}</h2>

<hr />

<div class="ui modal myModal">
    <i class="close icon"></i>
    <div class="header">
        Profile Picture
    </div>
    <div class="image content">
        <div class="ui medium image">
            <img src={{ profile.avatar.url }}>
        </div>
        <div class="description">
            <div class="ui header">Provide your details</div>
            <form action="" method="post" class="ui form" enctype="multipart/form-data">
                {% csrf_token %} {{ form.as_p }}
        </div>
    </div>
    <div class="actions">
        <button type='submit' class="ui positive right labeled icon button">
            Update
            <i class="checkmark icon"></i>
        </button>
        </form>
    </div>
</div>


<div class="ui segment">
    {% if confirm %}
        <div class="ui green message">Your profile has been updated</div>
    {% endif %}
    <h3>my profile: {{request.user}}</h3>
    <div class="ui grid">
        <div class='row'>
            <div class='six wide column'>
                <img class="ui medium rounded image" src={{profile.avatar.url}}>
                <div class="row mt-5">
                    <button class='ui secondary button' id='modal-btn'>Update your profile</button>
                </div>
            </div>
            <div class="ten wide column">
                <table class="ui table">
                    <tbody>
                        <tr>
                            <td>username</td>
                            <td>{{profile.user}}</td>
                        </tr>
                        <tr>
                            <td>first name</td>
                            <td>{{profile.first_name}}</td>
                        </tr>
                        <tr>
                            <td>last name</td>
                            <td>{{profile.last_name}}</td>
                        </tr>
                        <tr>
                            <td>bio</td>
                            <td>{{profile.bio}}</td>
                        </tr>
                        <tr>
                            <td>number of friends</td>
                            <td>{{profile.get_friends_no}}</td>
                        </tr>
                        <tr>
                            <td>number of friends</td>
                            <td>
                                <ul>
                                    {% for friend in profile.get_friends %}
                                        <li>{{friend}}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>number of posts</td>
                            <td>{{profile.get_posts_no}}</td>
                        </tr>
                        <tr>
                            <td>number of likes given</td>
                            <td>{{profile.get_likes_given_no}}</td>
                        </tr>
                        <tr>
                            <td>number of likes received</td>
                            <td>{{profile.get_likes_recieved_no}}</td>
                        </tr>

                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No invitations yet</h1>
    {% endif %}
    {% for obj in qs %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class='ui small circular image' src={{ obj.avatar.url }} />
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="">
                            <button class="ui button primary mb-5 w-big">See profile</button>
                        </a>
                        <form action={% url 'profiles:accept-invitation-view' %} method="post">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{ obj.id }}>
                                <button class='ui positive basic button mb-5 w-big' type="submit">
                                    <i class='checkmark icon'></i>
                                    Accept invite
                                </button>
                        </form>
                        <form action={% url 'profiles:reject-invitation-view' %} method="post">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{ obj.id }}>
                                <button class='ui negative basic button mb-5 w-big' type="submit">
                                    <i class='close icon'></i>
                                    Reject invite
                                </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

profiles/templates/profiles/profile_detail.html
{% extends 'base.html' %}

{% block title %}
profile detail
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src={{object.avatar.url}}>
            <h1>{{object.user}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ object.get_posts_no }}</div>
                </div>
                <div class="item">
                    Likes given
                    <div class="ui label">{{ object.get_likes_given_no }}</div>
                </div>
                <div class="item">
                    Likes received
                    <div class="ui label">{{ object.get_likes_recieved_no }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ object.get_friends_no }}</div>
                </div>
            </div>
            {% if object.user not in rel_reciver and object.user not in rel_sender %}
                <form action={% url 'profiles:send-invite-view' %} method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{ object.id }}>
                    <button class='ui positive basic button mb-5 w-big' type="submit">
                        <i class='plus square icon'></i>
                        Add friends
                    </button>
                </form>
            {% endif %}
            {% if object.user in rel_reciver and request.user not in object.friends.all %}
                <button class='ui disabled button mb-5 w-big' type="submit">
                    <i class='user icon'></i>
                    Waiting for approval
                </button>
            {% endif %}   
            {% if request.user in object.friends.all %}
                <form action={% url 'profiles:remove-friends-view' %} method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{ object.id }}>
                    <button class='ui negative baisc button mb-5 w-big' type="submit">
                        <i class='minus square icon'></i>
                        Remove from friends
                    </button>
                </form>
            {% endif %}
        </div>
        <div class="twelve wide column">
            {% if len_posts %}
                {% for post in posts %}
                    <div class="segment ui fluid">
                        {{post.content}}
                    </div>
                {% endfor %}
            {% else %}
                <h1>No posts of this user ...</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/profiles_list.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h2>No profiles to interact with</h2>
    {% else %}
        {% for item in qs %}
            <div class="ui segment">
                <div class="ui grid">
                    <div class="row">
                        <div class="three wide column">
                            <img class="ui small circular image" src={{ item.avatar.url }} />
                        </div>
                        <div class="thirteen wide column">
                            <h3>{{ item.user }}</h3>
                            <p>{{ item.bio }}</p>
                            <a href={{item.get_absolute_url}}>
                                <button class="ui button primary mb-5 w-big">See profile</button>
                            </a>
                            <br>
                            {% if item.user not in rel_reciver and item.user not in rel_sender %}
                               <form action={% url 'profiles:send-invite-view' %} method="post">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{ item.id }}>
                                    <button class='ui positive basic button mb-5 w-big' type="submit">
                                        <i class='plus square icon'></i>
                                        Add friends
                                    </button>
                                </form>
                            {% endif %}
                            {% if item.user in rel_reciver and request.user not in item.friends.all %}
                                <button class='ui disabled button mb-5 w-big' type="submit">
                                    <i class='user icon'></i>
                                    Waiting for approval
                                </button>
                            {% endif %}   
                            {% if request.user in item.friends.all %}
                                <form action={% url 'profiles:remove-friends-view' %} method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value={{ item.id }}>
                                        <button class='ui negative baisc button mb-5 w-big' type="submit">
                                            <i class='minus square icon'></i>
                                            Remove from friends
                                        </button>
                                </form>
                            {% endif %}
                    </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

profiles/templates/profiles/to_invite_profiles_list.html
{% extends 'base.html' %}

{% block title %}
to invite
{% endblock title %}

{% block content %}

<ul>

    {% for item in qs %}
        <li>{{ item }}</li>
    {% endfor %}
   
</ul>
{% endblock content %}